name: Run trivy scan on docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Build, tag and cache image locally
        run: |
          docker buildx create --use

          docker buildx build \
            --load \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            -t giobt/${{ inputs.image_name }}:${{ inputs.image_tag }} \
            .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: rolla/${{ inputs.image_name }}:${{ inputs.image_tag }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"


      